### ISSUE TITLE
enable lazy loading via conditional loading of dependencies

### ISSUE THREAD

**Issue by AndreasGalster** [meteorwebcomponents/synthesis#10]
Right now synthesis seems to build everything automatically into app.js.
Not sure if this is a synthesis specific issue or a meteor issue.

This makes it impossible to truly only load a dependency to the client when the route is needed and clashes with the soon coming conditional import syntax within meteor as well as lazy loading with Polymer with the PRPL pattern encouraged by Google.

Is there a way to get true conditional loading of dependencies working?

**Comment by aruntk** [comment]
This is a meteor specific issue. Meteor does not have a native lazy loading system right now. This makes it difficult to right now. But at some time in the future they will likely make lazy load/evaluation the default behavior in meteor. We'll able to use that feature to add lazy loading in synthesis also.

**Comment by aruntk** [comment]
closing in favour of #16 and #17
