### ISSUE TITLE
How to use Polymer 2.0 ? 

### ISSUE THREAD

**Issue by romans127** [meteorwebcomponents/synthesis#14]
Greetings, 

Does this package use Polymer 2.0 and if not how would I integrate polymer 2.0 ?

**Comment by aruntk** [comment]
Synthesis does not use polymer at all. It helps you to write polymer code inside your meteor directories. ie You can copy your existing polymer element/app and paste inside meteor directories and it will work. Synthesis will take care of all the html,css,js imports. You can use any version of polymer. Checkout [this app](https://github.com/aruntk/kickstart-meteor-polymer) for more details.
To upgrade to polymer 2.0 all you need to do is to install v2.0 using bower and import that. Of course you'll have to make necessary changes in your polymer elements to upgrade to 2.0. But then thats not part of synthesis' working.

**Comment by romans127** [comment]
Awesome thank you for providing that insight.
