### ISSUE TITLE
Reactive Data and Masonry

### ISSUE THREAD

**Issue by bhdzllr** [meteorwebcomponents/synthesis#21]
Hello Arun,

I'm using Synsthesis and trying to use Masonry (http://masonry.desandro.com/) to lay out my grid. But it seems there is a timing problem.

If I do something like that:

```
    <div id="grid">
      <template is="dom-repeat" id="items" items="{{items}}" as="item">
        <paper-card class="grid-item" heading="[[item.name]]">
          <div class="card-content">
              <div>[[item.text]]</div>
          </div>
        </paper-card>
      </template>
    </div>
```

How do I know if the DOM is ready to initialize Masonry, and how do I know if data changes are finished, because I need to perform an Masonry action if items array changes. If I initialize Masonry in the "ready()" function I need a timeout (about 200 ms) to properly lay out my elements. If I observe changes (or call Masonry in tracker function) I also need a timeout.

Timeout is not optimal because you see the rearrangment of elements (especially when new elements are added) and sometimes it doesn't work with hot code push.

Do you have any ideas how I can fix this? I think Meteor with Blaze has "onRendered()" for stuff like that?

Thank you for your time.

**Comment by aruntk** [comment]
@bhdzllr Observer callbacks are called after a data change. Theoretically this -> `'itemsChanged(items.*)'` should work.  I'm not sure what you meant by 
> how do I know if data changes are finished

If you are getting the data as the result of a subscription you can call the masonry function inside the subscription callback.

> DOM is ready to initialize Masonry

By this do you mean you want to know when the template repeat completes the looping and rendering of inner elements? If that is the case I think the event [dom-change](https://www.polymer-project.org/1.0/docs/api/dom-repeat#event-dom-change) can be used. 

```
<div id="grid">
  <template is="dom-repeat" id="items" items="{{items}}" as="item" on-dom-change="domChange">
    <paper-card class="grid-item" heading="[[item.name]]">
      <div class="card-content">
        <div>[[item.text]]</div>
      </div>
    </paper-card>
  </template>
</div>
```
And then do what you want to do inside domChange method

**Comment by bhdzllr** [comment]
Thank you Arun.
With domChange I was able to restart Masonry, but still needed a Timeout.
I now use parts of https://github.com/blmarket/masonry-layout/ because I also want my Grid as a component and it seems to work.

Unfortunately I do need an async function to call Masonrys ".reloadItems()" and ".layout()" in the "attached" handler because sometimes layout does not work.

**Comment by aruntk** [comment]
I'm not sure why you need a timeout in dom-change callback. Do you have a publicly hosted source?

**Comment by bhdzllr** [comment]
Sorry, don't have it public but I created a Gist with the code:
~~https://gist.github.com/bhdzllr/6a850281532c7c61ab9a73ef83c776f8~~

Thank you for helping out.

**Comment by bhdzllr** [comment]
I do not know exactly why, but it works now without the first timeout.
Maybe it had something to do with styling (block elements, width and height).
