### ISSUE TITLE
Support for Meteor 1.5 dynamic imports?

### ISSUE THREAD

**Issue by faburem** [meteorwebcomponents/synthesis#22]
Will synthesis support dynamic imports [https://blog.meteor.com/dynamic-imports-in-meteor-1-5-c6130419c3cd#.fa128jrwd](https://blog.meteor.com/dynamic-imports-in-meteor-1-5-c6130419c3cd#.fa128jrwd)?
I believe this could make Meteor a great alternative to the Polymer CLI + Firebase. Currently the bundling of Meteor assets limits the benefits of using Polymer with Meteor to build progressive webapps.

**Comment by aruntk** [comment]
Here is a simple demo. Polymer + Meteor Dynamic imports - https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/tree/dynamic-import

relevant code 

https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/blob/dynamic-import/imports/ui/layouts/test-layout.js#L27-L36

**Comment by faburem** [comment]
This is amazing! Thank you very much for the demo.

Just one more question: is there a reason why you dynamically import the html and inline the script here: [https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/blob/dynamic-import/imports/ui/components/test-element.html#L3](https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/blob/dynamic-import/imports/ui/components/test-element.html#L3)
or would this work the same way if you dynamically import the js and have a regular import of the html at the top?

Maybe I'm missing something, so I'm grateful for your feedback.

**Comment by aruntk** [comment]
@faburem 

Yes. It would work the same way. 

One thing to note here is that you should follow this format.

```js
import('../components/test-element.html').then(bundle => {
  console.log('test element fetched');
});
```
```js
const href = `../components/test-element.html`;
import(href).then(bundle => {
   console.log('test element fetched');
});
```
This doesn't seem to be working. I think the reason for this is they are simply using AST based code parsing to detect this format import('href inside') and precompile the href.

**Comment by faburem** [comment]
Thank you very much. You've built something great with synthesis, keep up the good work.

**Comment by aruntk** [comment]
@faburem Thank you for the kind words. :)
