### ISSUE TITLE
Cursor handling like blaze

### ISSUE THREAD

**Issue by yorrd** [meteorwebcomponents/synthesis#23]
Hi! This has been on my mind for a few weeks now but I'm too inexperienced in how synthesis works exactly, so I'm asking you whether this is possible. 

Basically, I read the tutorial for blaze out of boredom and I noticed, that blaze can handle mongo cursors directly. If I understand correctly, you take the cursor and hand it to the blaze iterator which then works like a dom-repeat. 

This of course doesn't work in Polymer because Polymer just isn't made for mongo cursors. But do you think it is possible to add a layer between the polymer dom repeat (or whatever) and the mongo cursor which basically does all the observing and updates automatically? At the moment, writing changes from the app back to the database for example is a pain in the ass and could be much easier if we could just directly connect mongo with the polymer components. 

Thanks for any advice. I'd be happy to help here, but as I said, not very familiar with the inner workings of synthesis yet.

**Comment by aruntk** [comment]
@yorrd We already have a project for polymer-meteor data. https://github.com/meteorwebcomponents/mixin

**Comment by yorrd** [comment]
@aruntk I don't quite understand. Maybe I didn't get the concept of getMeteorData yet. Could you kindly show me in a few lines how you would use a mongodb cursor directly in a dom-repeat so that you don't need to write the `.fetch()` yourself, thus making it non-reactive? 

```
<template is="dom-repeat" item="{{whatToPutHere}}">
    {{item}}
</template>
```

**Comment by yorrd** [comment]
@aruntk Im sorry, overlooked the part in the documentation. For everyone wondering: https://github.com/meteorwebcomponents/mixin/blob/master/README.md#getmeteordata

**Comment by aruntk** [comment]
@yorrd Use https://github.com/meteorwebcomponents/mixin/blob/master/README.md#trackers instead.

**Comment by aruntk** [comment]
@yorrd https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/blob/master/imports/ui/layouts/test-layout.js#L20-L26

https://github.com/aruntk/kickstart-meteor-polymer-with-app-route/blob/master/imports/ui/layouts/test-layout.html#L30

**Comment by yorrd** [comment]
@aruntk okay now I can neatly show content from my database

```
    this.subscribe("boxes");
    this.set("myself", Boxes.findOne({_id: this.boxId}));
```

but that's not a double data binding. So when I have an `<input/>` and I map something from `myself` to it as in

```
    <iron-input bind-value="{{myself.title}}" id="title" class="flex">
        <input value="{{value::input}}"/>
    </iron-input>
```

then changing the input won't change the database. Is there a solution for that as well?

**Comment by aruntk** [comment]
@yorrd We don't have any control over polymer bindings. Maybe if I dive into polymer's inner code then I might be able to find a solution. But then it'll become way too difficult to maintain. And I think it is both unnecessary(not much practical use) and dangerous to connect binding to a db field.

**Comment by yorrd** [comment]
@aruntk okay got it. Well, I'm using this kind of behavior quite frequently, that's why I came up with the idea. I totally get it though, that's maybe too deep into Polymer. If I get around to it, I'll try and share my experience with forking synthesis. For now I'll take it the way it is and finish the project first ;) 

Thanks for all the good work and quick update to Polymer 2.0 btw! :heart:
