### ISSUE TITLE
Uncaught TypeError: callbackQueue.shift(...) is not a function

### ISSUE THREAD

**Issue by wojtkowiak** [meteorwebcomponents/synthesis#3]
The `Synthesis.body._render` you are using in Meteor.startup is not wrapped in a function. Therefore a lot of 
`Uncaught TypeError: callbackQueue.shift(...) is not a function`
errors are visible in the console. `Synthesis.body._render` returns `true` which is passed to Meteor.startup.

**Comment by aruntk** [comment]
Fixed with the latest commit.
