### ISSUE TITLE
Question about Tracker and Mobile versions

### ISSUE THREAD

**Issue by iSuslov** [meteorwebcomponents/synthesis#7]
1) I have a question if this package has the same cordova support as any other meteor official (Blaze, React, Angular)?

2) Are we still able to use Tracker?

**Comment by aruntk** [comment]
First of all sorry for the delay in answering the question. 
1. Yes. Synthesis works perfectly fine in cordova. 
Here is a kickstarter app for testing the same https://github.com/aruntk/kickstart-meteor-polymer. 
kickstarter with auth https://github.com/aruntk/kickstart-meteor-polymer-with-auth
2. Do you mean tracker inside polymer elements? No issues here also. Everything works as expected. We've got a meteor polymer data mixin library [mwc:mixin](https://github.com/meteorwebcomponents/mixin). Its included in the kickstarter app. Also there is [mwc:router](https://github.com/meteorwebcomponents/router) for reactive routing from within polymer components.

**Comment by aruntk** [comment]
Closing the issue.
