### ISSUE TITLE
Trying to run polymer shop demo. Errors

### ISSUE THREAD

**Issue by iSuslov** [meteorwebcomponents/synthesis#8]
First error I got:

```
template.polymer-micro.js:331 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.(anonymous function) @ template.polymer-micro.js:331
```

Than chain of other errors, probably related to the first one.

My application structure looks like this:

![screen shot 2016-05-24 at 15 11 38](https://cloud.githubusercontent.com/assets/7628774/15498579/ff36a176-21c1-11e6-83f0-d4f42ad55bb6.png)

main.html

```
<head>
    <title>Synthesis</title>
    <style>
        body {
            padding: 0px;
            margin: 0px;
        }
    </style>
</head>
<body class="fullbleed">
<shop-app unresolved>SHOP</shop-app>

    <script>
        window.performance && performance.mark && performance.mark('index.html');

        Polymer = {lazyRegister: true, dom: 'shadow'};

        (function () {
            if ('registerElement' in document
                    && 'import' in document.createElement('link')
                    && 'content' in document.createElement('template')) {
                // platform is good!
            } else {
                // polyfill the platform!
                var e = document.createElement('script');
                e.src = '/bower_components/webcomponentsjs/webcomponents-lite.min.js';
                document.body.appendChild(e);
            }
        })();
    </script>
</body>

```

main.js

```
//import '../imports/ui/bower_components/webcomponentsjs/webcomponents-lite.min.js'
import "../imports/ui/bower_components/polymer/polymer.html";
//import "../../ui/bower_components/mwc-layout/mwc-layout.html"; //if you are using bower for mwc-layout

import '../imports/ui/src/shop-app.html';
//import '../imports/startup/client/router.js';

```

Errors I have:

![screen shot 2016-05-24 at 15 14 18](https://cloud.githubusercontent.com/assets/7628774/15498645/3f7c1860-21c2-11e6-8fcb-01173cf8b0f8.png)

**Comment by aruntk** [comment]
@iSuslov Do you have a public repo for the app? I think this happens because polymer is getting added twice from two separate source urls.

**Comment by iSuslov** [comment]
This is polymer demo, available here https://github.com/Polymer/shop

**Comment by aruntk** [comment]
this import is causing the errors. `<link rel="import" href="../bower_components/app-route/app-route.html">`

**Comment by iSuslov** [comment]
But how to use native polymer routing? I found it better than kadira flow router.

**Comment by aruntk** [comment]
Maybe its not the issue with routing. This is my theory. Error happens when the router renders an element. When I disabled the app router import no route is selected. Which means no elements are rendered except the header and footer. I'm digging deeper into the app.

Disabling this also stops the error log.

``` js
    <app-route
        route="{{route}}"
        pattern="/:page"
        data="{{routeData}}"
        tail="{{subroute}}"></app-route>
```

**Comment by aruntk** [comment]
`_ensureLazyLoaded` error is in this function. There is some issue with lazyloading.maybe because lazy-resource.html and service-worker.js are not included

**Comment by aruntk** [comment]
ya. thats the issue. this.resolveUrl('lazy-resources.html')) results in http://localhost:3000/lazy-resources.html which is absent. if you import this file you can solve the issue. 

``` js
Polymer.RenderStatus.afterNextRender(this, function() {
require("./lazy-resources.html");
              // Register service worker if supported.

              if ('serviceWorker' in navigator) {
                navigator.serviceWorker.register('/service-worker.js');
              }
              this._notifyNetworkStatus();
              this.loadComplete = true;
          });
```
